version: '3'
env:
  PORT: '{{.PORT | default "8080"}}'
  HOST: '{{.HOST | default "localhost"}}'
  BINARY: '{{.BINARY | default "todo-service.bin"}}'

tasks:
  todo:
    vars:
      JSON: '{ "description": "Todo string", "title": "Todo string" }'
    cmds:
      - "curl -X POST 'http://{{.HOST}}:{{.PORT}}/todo' -H 'Content-Type: application/json' -d '{{.JSON}}'"

  list:
    cmds:
      - "curl -X GET 'http://{{.HOST}}:{{.PORT}}/todo' -H 'accept: */*' | jq ."

  swagger:
    cmds:
      - "cd todo-service; swag init"
    sources:
      - todo-service/**/*.go
    generates:
      - todo-service/docs/swagger.yaml

  vet:
    cmds:
      - "cd todo-service; go vet"

  test:
    cmds:
      - hurl --test todo.hurl

  build:
    cmds:
      - "cd todo-service; GO111MODULE=on; go mod download; go build -o {{.BINARY}}"
    sources:
      - todo-service/**/*.go
    generates:
      - todo-service/{{.BINARY}}

  run:
    deps: [build]
    cmds:
      - "./todo-service/{{.BINARY}}"

  clean:
    cmds:
      - "rm -rf ./todo-service/{{.BINARY}}"
