version: '3'
env:
  PORT: '{{.PORT | default "8080"}}'
  HOST: '{{.HOST | default "localhost"}}'
  BINARY_FILE: '{{.BINARY_FILE | default "todo-service.bin"}}'
  SBOM_FILE: '{{.SBOM_FILE | default "sbom.json"}}'
  REGISTRY_URL: '{{.REGISTRY_URL | default "127.0.0.1:5000"}}'
  USERNAME: '{{.USERNAME | default "user"}}'
  PASSWORD: '{{.PASSWORD | default "test"}}'
  VERSION: '{{.VERSION | default "latest"}}'
  ARTIFACT_NAME: '{{.ARTIFACT_NAME | default "todo-service"}}'
  ARTIFACT_TYPE: '{{.ARTIFACT_TYPE | default "application/vnd.oci.image.layer.v1.tar"}}'

includes:
  registry:
    taskfile: ./taskfiles/Taskfile-registry.yml
  oras:
    taskfile: ./taskfiles/Taskfile-oras.yml
  cosign:
    taskfile: ./taskfiles/Taskfile-cosign.yml
  sbom:
    taskfile: ./taskfiles/Taskfile-sbom.yml

tasks:
  todo:
    vars:
      JSON: '{ "description": "Todo string", "title": "Todo string" }'
    cmds:
      - "curl -X POST 'http://{{.HOST}}:{{.PORT}}/todo' -H 'Content-Type: application/json' -d '{{.JSON}}'"

  list:
    cmds:
      - "curl -X GET 'http://{{.HOST}}:{{.PORT}}/todo' -H 'accept: */*' | jq ."

  swagger:
    cmds:
      - "cd todo-service; swag init"
    sources:
      - todo-service/**/*.go
    generates:
      - todo-service/docs/swagger.yaml

  vet:
    cmds:
      - "cd todo-service; go vet"

  test:
    cmds:
      - hurl --test todo.hurl

  build:
    cmds:
      - "cd todo-service; GO111MODULE=on; go mod download; go build -o {{.BINARY_FILE}}"
    sources:
      - todo-service/**/*.go
    generates:
      - todo-service/{{.BINARY_FILE}}

  ko:
    cmds:
      - "cd todo-service; KO_DOCKER_REPO={{.REGISTRY_URL}}/{{.ARTIFACT_NAME}} ko build ."

  sbom:
    cmds:
      - ""

  run:
    deps: [build]
    cmds:
      - "./todo-service/{{.BINARY_FILE}}"

  install:
    cmds:
      - "go install github.com/swaggo/swag/cmd/swag@latest"
      - "go install braces.dev/errtrace/cmd/errtrace@latest"
      - "go install github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod@latest"
      - "go install github.com/google/ko@latest"

  clean:
    cmds:
      - "rm -rf ./todo-service/{{.BINARY_FILE}}"
      - "rm -rf ./todo-service/{{.SBOM_FILE}}"
