version: '3'
env:
  BINARY: '{{.BINARY | default "todo-service.bin"}}'

tasks:
  harbor:
    cmds:
      - |
        podman run --rm  \
          -it docker.io/bitnami/oras:latest \
          sh -c "cd {{.MOUNT_PATH}} && ln -s asciidoc/src/site/asciidoc/spec spec \
            && openapi-generator-cli generate -g asciidoc \
            --skip-validate-spec \
            --release-note='{{.RELEASE_NOTES}}' \
            --input-spec=asciidoc/src/site/asciidoc/spec/openapi.json \
            --output=asciidoc/src/site/asciidoc \
            --additional-properties=specDir=spec/,useIntroduction=true,licenseInfo='{{.LICENSE_INFO}}' \
          && unlink spec"

  oras:
    cmds:
      - |
        podman run --rm  \
          -it docker.io/bitnami/oras:latest \
          sh -c "cd {{.MOUNT_PATH}} && ln -s asciidoc/src/site/asciidoc/spec spec \
            && openapi-generator-cli generate -g asciidoc \
            --skip-validate-spec \
            --release-note='{{.RELEASE_NOTES}}' \
            --input-spec=asciidoc/src/site/asciidoc/spec/openapi.json \
            --output=asciidoc/src/site/asciidoc \
            --additional-properties=specDir=spec/,useIntroduction=true,licenseInfo='{{.LICENSE_INFO}}' \
          && unlink spec"
    sources:
      - asciidoc/src/site/asciidoc/spec/openapi.json
    generates:
      - asciidoc/src/site/asciidoc/index.adoc
