version: '3'

tasks:
  container:
    internal: true
    cmds:
      - |
        podman run --rm -v .:/workspace -it --name oras --network=host \
          ghcr.io/oras-project/oras:main {{.ARGS}} --plain-http

  push:
    deps: [build]
    cmds:
      - task: container
        vars: { ARGS: "push --artifact-type {{.ARTIFACT_TYPE}} {{.REGISTRY_URL}}/{{.ARTIFACT_NAME}}:{{.VERSION}} todo-service/{{.BINARY}}" }

  pull:
    cmds:
      - task: container
        vars: { ARGS: "pull {{.REGISTRY_URL}}/{{.ARTIFACT_NAME}}:{{.VERSION}}" }

  blob:
    deps: [build]
    cmds:
      - task: container
        vars: { ARGS: "blob push --descriptor --pretty {{.REGISTRY_URL}}/{{.ARTIFACT_NAME}} todo-service/{{.BINARY}}" }

  sbom:
    deps: [sbom-cyclonex]
    cmds:
      - task: container
        vars: { ARGS: "attach --artifact-type application/vnd.unknown.config.v1+json {{.REGISTRY_URL}}/{{.ARTIFACT_NAME}}:{{.VERSION}} sbom.json" }

  annotate:
    cmds:
      - task: container
        vars: { ARGS: "push --annotation {{.ARGS}} {{.REGISTRY_URL}}/{{.ARTIFACT_NAME}}:{{.VERSION}} todo-service/{{.BINARY}}" }

  list:
    cmds:
      - task: container
        vars: { ARGS: "repo list {{.REGISTRY_URL}}" }

  discover:
    cmds:
      - task: container
        vars: { ARGS: "discover {{.REGISTRY_URL}}/{{.ARTIFACT_NAME}}:{{.VERSION}}" }