version: '3'
env:
  REGISTRY_URL: '{{.REGISTRY_URL | default "localhost:8000"}}'
  USERNAME: '{{.USERNAME | default "user"}}'
  PASSWORD: '{{.PASSWORD | default "test"}}'

tasks:
  oras:
    cmds:
      - |
        podman run --rm -v .:/workspace -it --name oras \
          ghcr.io/oras-project/oras:latest {{.ARGS}}

  oras-login:
    cmds:
      - task: oras
        vars: { ARGS: "login -u {{.USERNAME}} -p {{.PASSWORD}} {{.REGISTRY_URL}}" }

  registry:
    cmds:
      - |
        podman run --rm -it --name registry \
          -v ./infrastructure/config.toml:/config.toml \
          -p 8000:8000 \
          ghcr.io/simple-registry/simple-registry:main \
          simple-registry server
