// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"github.com/unexist/showcase-microservices-golang/adapter"
	"github.com/unexist/showcase-microservices-golang/domain"
)

// Injectors from wire.go:

func InitializeResource() *adapter.TodoResource {
	todoFakeRepository := NewTodoFakeRepository()
	todoService := domain.NewTodoService(todoFakeRepository)
	todoResource := adapter.NewTodoResource(todoService)
	return todoResource
}
